# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Log event')),
                ('type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Event Type')),
                ('card_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Card Type')),
                ('status_message', models.CharField(blank=True, max_length=400, null=True, verbose_name='Status Message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Transferred'), (3, 'Transfer Reversal'), (4, 'Payout Failed'), (5, 'Check Pending'), (6, 'Check Transferred')], db_index=True, default=1, verbose_name='Transaction Status')),
                ('fan_charged', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fan Charged')),
                ('stripe_processing_fees', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Stripe charges')),
                ('starsona_company_charges', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Starsona company charges')),
                ('fund_payed_out', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fund Payed Out')),
                ('stripe_transaction_id', models.CharField(blank=True, max_length=30, verbose_name='Transaction ID')),
                ('stripe_response', models.TextField(blank=True, max_length=1500, verbose_name='Stripe Response')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('comments', models.TextField(blank=True, max_length=200, verbose_name='Comments')),
                ('referral_payout', models.BooleanField(default=False, verbose_name='Referral Payout')),
            ],
        ),
        migrations.CreateModel(
            name='StarsonaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('transaction_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Authorized'), (3, 'Captured'), (4, 'Cancelled'), (5, 'Refunded'), (6, 'Failed')], db_index=True, default=1, verbose_name='Transaction Status')),
                ('source_id', models.CharField(max_length=120)),
                ('stripe_transaction_id', models.CharField(max_length=120)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, max_length=200, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('response', models.TextField(blank=True, max_length=1500, verbose_name='Response')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
