# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('stargramz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_celebrity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='starsonatransaction',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_celebrity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='starsonatransaction',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='starsonatransaction',
            name='starsona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_transaction', to='stargramz.Stargramrequest'),
        ),
        migrations.AddField(
            model_name='paymentpayout',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_celebrity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentpayout',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payout', to='payments.StarsonaTransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='starsonatransaction',
            unique_together=set([('starsona', 'celebrity'), ('starsona', 'fan')]),
        ),
    ]
