# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippayment',
            name='payed_out_response',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Payed out response'),
        ),
        migrations.AddField(
            model_name='tippayment',
            name='payed_out_transaction_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Payed out transaction'),
        ),
        migrations.AddField(
            model_name='tippayment',
            name='tip_payed_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tip payed out'),
        ),
        migrations.AlterField(
            model_name='tippayment',
            name='source_id',
            field=models.CharField(max_length=120, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='tippayment',
            name='stripe_transaction_id',
            field=models.CharField(max_length=120, verbose_name='Transaction ID'),
        ),
    ]
