# Generated by Django 2.1.5 on 2019-02-28 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20181217_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsonatransaction',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Stripe'), (2, 'InApp')], db_index=True, default=1, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='paymentpayout',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_celebrity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentpayout',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_payout', to='payments.StarsonaTransaction'),
        ),
        migrations.AlterField(
            model_name='starsonatransaction',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_celebrity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='starsonatransaction',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_fan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='starsonatransaction',
            name='starsona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_transaction', to='stargramz.Stargramrequest'),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_celebrity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tippayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tip_payment', to='stargramz.Stargramrequest'),
        ),
        migrations.AlterField(
            model_name='tippayment',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tip_celebrity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tippayment',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tip_fan', to=settings.AUTH_USER_MODEL),
        ),
    ]
