# Generated by Django 2.1.5 on 2019-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20190405_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsonatransaction',
            name='ambassador_transaction',
            field=models.BooleanField(default=False, verbose_name='Ambassador Transaction'),
        ),
        migrations.AlterField(
            model_name='starsonatransaction',
            name='celebrity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_celebrity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='starsonatransaction',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_fan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='starsonatransaction',
            unique_together=set(),
        ),
    ]
