# Generated by Django 2.1.5 on 2019-04-05 12:02

from django.db import migrations, transaction
from payments.models import PAYMENT_TYPES
from job.tasks import verify_referee_discount


def actual_amount_initializer(apps, schema_editor):
    TransactionModel = apps.get_model('payments', 'StarsonaTransaction')
    transactions = TransactionModel.objects.all()
    try:
        with transaction.atomic():
            for star_transaction in transactions:
                if star_transaction.amount:
                    if star_transaction.payment_type is PAYMENT_TYPES.in_app:
                        amount = round((float(star_transaction.amount) * (70.0 / 100.0)), 2)
                    else:
                        amount = float(star_transaction.amount)
                    referee_discount = verify_referee_discount(star_transaction.celebrity_id)
                    star_transaction.actual_amount = round((float(amount) * (referee_discount / 100.0)), 2)
                else:
                    star_transaction.actual_amount = 0.0
                star_transaction.save()
    except Exception as e:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20190405_1151'),
    ]

    operations = [
        migrations.RunPython(actual_amount_initializer)
    ]
