# Generated by Django 2.1.5 on 2019-04-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20190405_1202'),
        ('payments', '0007_merge_20190321_0547'),
    ]

    operations = [
    ]
