# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='has_requested_referral',
            field=models.BooleanField(default=False, verbose_name='Referral requested'),
        ),
    ]
