# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_celebrity_has_requested_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='has_requested_referral',
        ),
        migrations.AddField(
            model_name='stargramzuser',
            name='has_requested_referral',
            field=models.BooleanField(default=False, verbose_name='Referral requested'),
        ),
    ]
