# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180724_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Stripe User ID'),
        ),
    ]
