# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stargramzuser_stripe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='check_payments',
            field=models.BooleanField(default=False, verbose_name='Check Payment'),
        ),
    ]
