# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 08:56
from __future__ import unicode_literals

from django.db import migrations


def migrate_stripe_user_id(apps, schema_editor):

    celebrity = apps.get_model("users", "Celebrity")
    users = apps.get_model('users', 'StargramzUser')
    for celebrity_user in celebrity.objects.all():
        if celebrity_user.stripe_user_id:
            try:
                customer = users.objects.get(id=celebrity_user.user_id)
                if not customer.stripe_user_id:
                    customer.stripe_user_id = celebrity_user.stripe_user_id
                    customer.save()
            except Exception as e:
                print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stargramzuser_stripe_user_id'),
    ]

    operations = [
        migrations.RunPython(migrate_stripe_user_id)
    ]
