# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 08:25
from __future__ import unicode_literals

from django.db import migrations
from django.core.mail import send_mail

def migrate_stripe_user_id(apps, schema_editor):

    celebrity = apps.get_model("users", "Celebrity")
    users = apps.get_model('users', 'StargramzUser')
    for celebrity_user in celebrity.objects.all():
        if celebrity_user.stripe_user_id:
            try:
                customer = users.objects.get(id=celebrity_user.user_id)
                if not customer.stripe_user_id:
                    customer.stripe_user_id = celebrity_user.stripe_user_id
                if celebrity_user.check_payments:
                    customer.check_payments = True
                customer.save()
            except Exception as e:
                send_mail(
                    'Migrations',
                    str(e),
                    "info@starsona.com",
                    ['akhilns@qburst.com'],
                    fail_silently=False,
                    html_message=str(e)
                )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_stargramzuser_check_payments'),
    ]

    operations = [
        migrations.RunPython(migrate_stripe_user_id)
    ]
