# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-10 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180731_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vanity_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
