# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 08:59
from __future__ import unicode_literals

from django.db import migrations
from users.utils import generate_vanity_url


def migrate_generate_vanity_url(apps, schema_editor):

    users = apps.get_model('users', 'StargramzUser')
    vanity = apps.get_model('users', 'VanityUrl')

    try:
        vanity.objects.all().delete()
    except Exception:
        pass

    for user in users.objects.all():
        try:
            if not vanity.objects.filter(user_id=user.id).exists():
                code = generate_vanity_url(user)
                vanity.objects.create(name=code, user=user)
        except Exception as e:
            print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vanityurl'),
    ]

    operations = [
        migrations.RunPython(migrate_generate_vanity_url)
    ]

