# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-10 08:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180820_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanrating',
            name='reason',
            field=models.CharField(blank=True, max_length=260, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='fanrating',
            name='comments',
            field=models.CharField(blank=True, max_length=260, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='fanrating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='fanrating',
            name='fan_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Fan rating'),
        ),
    ]
