# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180910_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityavailablealert',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
