# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-24 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_celebrityavailablealert_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityGroupAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='Admin Approved')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='list order')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(blank=True, max_length=260, null=True, verbose_name='Contact first name')),
                ('contact_last_name', models.CharField(blank=True, max_length=260, null=True, verbose_name='Contact last name')),
                ('follow_count', models.IntegerField(blank=True, default=0, verbose_name='Followers')),
                ('group_type', models.IntegerField(choices=[(1, 'Charity'), (2, 'Brand')], db_index=True, default=0, verbose_name='Group Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tags', models.CharField(blank=True, max_length=260, null=True, verbose_name='Tags')),
                ('website', models.CharField(blank=True, max_length=260, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=260, null=True, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=260, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='State')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='Zip')),
                ('country', models.IntegerField(choices=[(-1, 'Select country'), (0, 'Afghanistan'), (1, 'Albania'), (2, 'Algeria'), (3, 'American Samoa'), (4, 'Andorra'), (5, 'Angola'), (6, 'Anguilla'), (7, 'Antarctica'), (8, 'Antigua And Barbuda'), (9, 'Argentina'), (10, 'Armenia'), (11, 'Aruba'), (12, 'Australia'), (13, 'Austria'), (14, 'Azerbaijan'), (15, 'Bahamas'), (16, 'Bahrain'), (17, 'Bangladesh'), (18, 'Barbados'), (19, 'Belarus'), (20, 'Belgium'), (21, 'Belize'), (22, 'Benin'), (23, 'Bermuda'), (24, 'Bhutan'), (25, 'Bolivia'), (26, 'Bosnia And Herzegovina'), (27, 'Botswana'), (28, 'Bouvet Island'), (29, 'Brazil'), (30, 'British Indian Ocean Territory'), (31, 'Brunei Darussalam'), (32, 'Bulgaria'), (33, 'Burkina Faso'), (34, 'Burundi'), (35, 'Cambodia'), (36, 'Cameroon'), (37, 'Canada'), (38, 'Cape Verde'), (39, 'Cayman Islands'), (40, 'Central African Republic'), (41, 'Chad'), (42, 'Chile'), (43, 'China'), (44, 'Christmas Island'), (45, 'Cocos (keeling) Islands'), (46, 'Colombia'), (47, 'Comoros'), (48, 'Congo'), (49, 'Congo, The Democratic Republic Of The'), (50, 'Cook Islands'), (51, 'Costa Rica'), (52, 'Cote Divoire'), (53, 'Croatia'), (54, 'Cuba'), (55, 'Cyprus'), (56, 'Czech Republic'), (57, 'Denmark'), (58, 'Djibouti'), (59, 'Dominica'), (60, 'Dominican Republic'), (61, 'East Timor'), (62, 'Ecuador'), (63, 'Egypt'), (64, 'El Salvador'), (65, 'Equatorial Guinea'), (66, 'Eritrea'), (67, 'Estonia'), (68, 'Ethiopia'), (69, 'Falkland Islands (malvinas)'), (70, 'Faroe Islands'), (71, 'Fiji'), (72, 'Finland'), (73, 'France'), (74, 'French Guiana'), (75, 'French Polynesia'), (76, 'French Southern Territories'), (77, 'Gabon'), (78, 'Gambia'), (79, 'Georgia'), (80, 'Germany'), (81, 'Ghana'), (82, 'Gibraltar'), (83, 'Greece'), (84, 'Greenland'), (85, 'Grenada'), (86, 'Guadeloupe'), (87, 'Guam'), (88, 'Guatemala'), (89, 'Guinea'), (90, 'Guinea-bissau'), (91, 'Guyana'), (92, 'Haiti'), (93, 'Heard Island And Mcdonald Islands'), (94, 'Holy See (vatican City State)'), (95, 'Honduras'), (96, 'Hong Kong'), (97, 'Hungary'), (98, 'Iceland'), (99, 'India'), (100, 'Indonesia'), (101, 'Iran, Islamic Republic Of'), (102, 'Iraq'), (103, 'Ireland'), (104, 'Israel'), (105, 'Italy'), (106, 'Jamaica'), (107, 'Japan'), (108, 'Jordan'), (109, 'Kazakstan'), (110, 'Kenya'), (111, 'Kiribati'), (112, 'Korea, Democratic Peoples Republic Of'), (113, 'Korea, Republic Of'), (114, 'Kosovo'), (115, 'Kuwait'), (116, 'Kyrgyzstan'), (117, 'Lao Peoples Democratic Republic'), (118, 'Latvia'), (119, 'Lebanon'), (120, 'Lesotho'), (121, 'Liberia'), (122, 'Libyan Arab Jamahiriya'), (123, 'Liechtenstein'), (124, 'Lithuania'), (125, 'Luxembourg'), (126, 'Macau'), (127, 'Macedonia, The Former Yugoslav Republic Of'), (128, 'Madagascar'), (129, 'Malawi'), (130, 'Malaysia'), (131, 'Maldives'), (132, 'Mali'), (133, 'Malta'), (134, 'Marshall Islands'), (135, 'Martinique'), (136, 'Mauritania'), (137, 'Mauritius'), (138, 'Mayotte'), (139, 'Mexico'), (140, 'Micronesia, Federated States Of'), (141, 'Moldova, Republic Of'), (142, 'Monaco'), (143, 'Mongolia'), (144, 'Montserrat'), (145, 'Montenegro'), (146, 'Morocco'), (147, 'Mozambique'), (148, 'Myanmar'), (149, 'Namibia'), (150, 'Nauru'), (151, 'Nepal'), (152, 'Netherlands'), (153, 'Netherlands Antilles'), (154, 'New Caledonia'), (155, 'New Zealand'), (156, 'Nicaragua'), (157, 'Niger'), (158, 'Nigeria'), (159, 'Niue'), (160, 'Norfolk Island'), (161, 'Northern Mariana Islands'), (162, 'Norway'), (163, 'Oman'), (164, 'Pakistan'), (165, 'Palau'), (166, 'Palestinian Territory, Occupied'), (167, 'Panama'), (168, 'Papua New Guinea'), (169, 'Paraguay'), (170, 'Peru'), (171, 'Philippines'), (172, 'Pitcairn'), (173, 'Poland'), (174, 'Portugal'), (175, 'Puerto Rico'), (176, 'Qatar'), (177, 'Reunion'), (178, 'Romania'), (179, 'Russian Federation'), (180, 'Rwanda'), (181, 'Saint Helena'), (182, 'Saint Kitts And Nevis'), (183, 'Saint Lucia'), (184, 'Saint Pierre And Miquelon'), (185, 'Saint Vincent And The Grenadines'), (186, 'Samoa'), (187, 'San Marino'), (188, 'Sao Tome And Principe'), (189, 'Saudi Arabia'), (190, 'Senegal'), (191, 'Serbia'), (192, 'Seychelles'), (193, 'Sierra Leone'), (194, 'Singapore'), (195, 'Slovakia'), (196, 'Slovenia'), (197, 'Solomon Islands'), (198, 'Somalia'), (199, 'South Africa'), (200, 'South Georgia And The South Sandwich Islands'), (201, 'Spain'), (202, 'Sri Lanka'), (203, 'Sudan'), (204, 'Suriname'), (205, 'Svalbard And Jan Mayen'), (206, 'Swaziland'), (207, 'Sweden'), (208, 'Switzerland'), (209, 'Syrian Arab Republic'), (210, 'Taiwan, Province Of China'), (211, 'Tajikistan'), (212, 'Tanzania, United Republic Of'), (213, 'Thailand'), (214, 'Togo'), (215, 'Tokelau'), (216, 'Tonga'), (217, 'Trinidad And Tobago'), (218, 'Tunisia'), (219, 'Turkey'), (220, 'Turkmenistan'), (221, 'Turks And Caicos Islands'), (222, 'Tuvalu'), (223, 'Uganda'), (224, 'Ukraine'), (225, 'United Arab Emirates'), (226, 'United Kingdom'), (227, 'United States'), (228, 'United States Minor Outlying Islands'), (229, 'Uruguay'), (230, 'Uzbekistan'), (231, 'Vanuatu'), (232, 'Venezuela'), (233, 'Viet Nam'), (234, 'Virgin Islands, British'), (235, 'Virgin Islands, U.s.'), (236, 'Wallis And Futuna'), (237, 'Western Sahara'), (238, 'Yemen'), (239, 'Zambia'), (240, 'Zimbabwe')], db_index=True, default=-1, verbose_name='Country')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='Admin Approved')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccountUser',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Brand/Charity',
                'indexes': [],
                'proxy': True,
            },
            bases=('users.stargramzuser',),
            managers=[
                ('objects', users.models.StargramzUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='groupaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celebritygroupaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celebritygroupaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
