# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180925_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
