# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181003_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link_key', models.CharField(max_length=255, verbose_name='Social media name')),
                ('social_link_value', models.CharField(blank=True, max_length=255, verbose_name='Social media URL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
