# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-10 11:14
from __future__ import unicode_literals

from django.db import migrations


def migration_update_referral_for_all(apps, schema_editor):

    users = apps.get_model('users', 'StargramzUser')
    campaign = apps.get_model('users', 'Campaign')

    try:
        campaignObj = campaign.objects.get(pk=2)
    except Exception:
        pass

    for user in users.objects.all():
        try:
            user.referral_campaign = campaignObj
            user.has_requested_referral = True
            user.referral_active = True
            user.save()
        except Exception as e:
            print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_socialmedialinks'),
    ]

    operations = [
        migrations.RunPython(migration_update_referral_for_all)
    ]
