# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_celebrityfollow_is_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebritygroupaccount',
            options={'verbose_name': 'Join Group', 'verbose_name_plural': 'Join Groups'},
        ),
    ]
