# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 11:32
from __future__ import unicode_literals
from django.db import migrations


def migration_update_groups_autoincrement_index(apps, schema_editor):
    """
    Alter the table to start auto increment from 2000
    :param apps:
    :param schema_editor:
    :return: Boolean
    """
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute("ALTER SEQUENCE users_grouptype_id_seq RESTART WITH 2000")
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20181026_0707'),
    ]

    operations = [
        migrations.RunPython(migration_update_groups_autoincrement_index)
    ]
