# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_representative'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profession',
            name='users_profe_title_8fe10b_idx',
        ),
        migrations.AddIndex(
            model_name='profession',
            index=models.Index(fields=['title', 'parent'], name='users_profe_title_5b2023_idx'),
        ),
    ]
