# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20181207_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='representative',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='representative',
            name='sms_verified',
            field=models.BooleanField(default=False, verbose_name='SMS Verified'),
        ),
    ]
