# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20181210_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='settingsnotifications',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
