# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-18 15:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20181212_0946'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='celebrityprofession',
            managers=[
                ('active_professions', django.db.models.manager.Manager()),
            ],
        ),
    ]
