# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-18 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20181218_1527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='celebrityprofession',
            managers=[
            ],
        ),
    ]
