# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20181218_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsnotifications',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsnotifications',
            name='verification_uuid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
