# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_stargramzuser_group_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='tw_id',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Twitter id'),
        ),
        migrations.AlterField(
            model_name='stargramzuser',
            name='sign_up_source',
            field=models.IntegerField(choices=[(1, 'Regular Sign-up'), (2, 'Facebook Sign-up'), (3, 'Google Sign-up'), (4, 'Instagram Sign-up'), (5, 'Twitter Sign-up')], default=1, verbose_name='Sign-up Source'),
        ),
    ]
