# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190128_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_owner_key', models.CharField(max_length=128)),
                ('resource_owner_secret', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
        ),
    ]
