# Generated by Django 2.1.5 on 2019-03-06 09:51

from django.db import migrations


def limit_in_app_price(apps, schema_editor):

    celebrity = apps.get_model('users', 'Celebrity')
    for star in celebrity.objects.all():
        try:
            if float(star.rate) > 1000:
                star.in_app_price = None
            star.save()
        except Exception as e:
            print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190226_1207'),
    ]

    operations = [
        migrations.RunPython(limit_in_app_price)
    ]
