# Generated by Django 2.1.5 on 2019-03-12 09:01

from django.db import migrations, models


def add_single_referral_code(apps, schema_editor):

    referral = apps.get_model('users', 'AdminReferral')
    referral_code = "911"
    try:
        referral.objects.get(id=1)
    except Exception:
        referral.objects.create(referral_code=referral_code)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20190306_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=100, verbose_name='Referral code')),
                ('activate', models.BooleanField(default=True, verbose_name='Activate')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
        ),
        migrations.AddField(
            model_name='stargramzuser',
            name='admin_approval_referral_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Approval referral code'),
        ),
        migrations.RunPython(add_single_referral_code)
    ]
