# Generated by Django 2.1.5 on 2019-03-14 05:24

from django.db import migrations, models
import django.db.models.deletion


def referral_code_changed_to_null(apps, schema_editor):
    """
    The referral code changed to null to avoid conflict between the existing values in the referral code and the new foreign key
    """
    User = apps.get_model('users', 'StargramzUser')
    try:
        users = User.objects.all()
        for user in users:
            user.admin_approval_referral_code = None
            user.save()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190312_0901'),
    ]

    operations = [
        migrations.RunPython(referral_code_changed_to_null),
        migrations.AlterField(
            model_name='stargramzuser',
            name='admin_approval_referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_referral', to='users.AdminReferral'),
        ),
    ]
