# Generated by Django 2.1.5 on 2019-03-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20190320_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='description'),
        ),
    ]
