# Generated by Django 2.1.5 on 2019-03-29 04:41

from django.db import migrations, models

def initialize_score(apps, schema_editor):
    celebrity = apps.get_model('users', 'Celebrity')
    celebrity_follow = apps.get_model('users', 'CelebrityFollow')
    bookings = apps.get_model('stargramz', 'Stargramrequest')

    celebrities = celebrity.objects.filter(admin_approval=True)
    for celebrity in celebrities:
        views = celebrity.view_count
        favorites = celebrity_follow.objects.filter(celebrity=celebrity.user).count()
        purchase = bookings.objects.filter(celebrity=celebrity.user).count()
        score = views + (5*favorites) + (10*purchase)
        celebrity.trending_star_score = score
        celebrity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_profession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='trending_star_score',
            field=models.IntegerField(blank=True, default=0, verbose_name='Star Score'),
        ),
        migrations.RunPython(initialize_score)
    ]
