# Generated by Django 2.1.5 on 2019-04-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_celebrity_trending_star_score'),
        ('users', '0036_auto_20190405_1126'),
    ]

    operations = [
    ]
