# Generated by Django 2.1.5 on 2019-04-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_celebrity_trending_star_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_star', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stargramzuser',
            name='is_ambassador',
            field=models.BooleanField(default=False, verbose_name='Is Ambassador'),
        ),
    ]
