# Generated by Django 2.1.5 on 2019-05-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_celebrity_average_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='temp_password',
            field=models.BooleanField(default=False, verbose_name='Temp Password'),
        ),
    ]
