# Generated by Django 2.1.5 on 2019-05-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_stargramzuser_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='medium_thumbnail',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Medium Thumbnail Image'),
        ),
    ]
