# Generated by Django 2.1.5 on 2019-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_profileimage_medium_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='migrated',
            field=models.BooleanField(default=False, verbose_name='Migrated'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='star_approved',
            field=models.BooleanField(default=True, verbose_name='Star Approved'),
        ),
    ]
