# Generated by Django 2.1.5 on 2019-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190524_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='profile_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Profile video'),
        ),
    ]
