# Generated by Django 2.1.5 on 2019-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_stargramzuser_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='reminder_mail_count',
            field=models.IntegerField(choices=[(0, 'No Mail'), (1, 'First Mail'), (2, 'Second Mail')], db_index=True, default=0, verbose_name='Reminder Mail count'),
        ),
    ]
