# Generated by Django 2.1.5 on 2019-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_stargramzuser_reminder_mail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramzuser',
            name='server_access_time_stamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Server access time stamp'),
        ),
    ]
