# Generated by Django 2.1.5 on 2019-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_stargramzuser_server_access_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration'),
        ),
    ]
