# Generated by Django 2.1.5 on 2019-06-17 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0016_stargramrequest_booking_statement'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0050_celebrity_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(choices=[(1, 'comment'), (2, 'reaction'), (3, 'tip'), (4, 'rating')], default=1, verbose_name='Activity Type')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('is_celebrity_activity', models.BooleanField(default=False, verbose_name='Is Celebrity Activity')),
                ('object_id', models.PositiveIntegerField()),
                ('activity_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_from', to=settings.AUTH_USER_MODEL)),
                ('activity_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_to', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_request', to='stargramz.Stargramrequest')),
            ],
        ),
    ]
