# Generated by Django 2.1.5 on 2019-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_recentactivity_public_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsnotifications',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
