# Generated by Django 2.1.5 on 2019-06-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20190621_0905'),
        ('users', '0054_auto_20190624_1116'),
    ]

    operations = [
    ]
