# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='specific_user',
            field=models.BooleanField(default=False, verbose_name='Specified users'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Promocode Status'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='users_per_coupon',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Users per coupon'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='uses_per_coupon',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Uses per coupon'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valide_from',
            field=models.DateField(verbose_name='Valide from'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valide_to',
            field=models.DateField(blank=True, verbose_name='Valide to'),
        ),
    ]
