# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.FileField(blank=True, null=True, upload_to='news/')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
        ),
    ]
