# Generated by Django 2.1.5 on 2019-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0002_auto_20190412_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebritydisplayorganizer',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
