# Generated by Django 2.1.5 on 2019-05-13 05:54

from django.db import migrations, models
import versioned.v2.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0003_celebritydisplayorganizer_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=versioned.v2.users.models.upload_function, verbose_name='Video')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
        ),
    ]
