# Generated by Django 2.1.5 on 2019-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0004_homepagevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='video_type',
            field=models.IntegerField(choices=[(1, 'Fan Video'), (2, 'Star Video')], default=2, verbose_name='Video Type'),
        ),
    ]
