# Generated by Django 2.1.5 on 2019-06-07 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users2', '0005_homepagevideo_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Total Earnings')),
                ('pending_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Pending Payments')),
                ('total_video_count', models.IntegerField(blank=True, default=0, verbose_name='Total Video Count')),
                ('total_comment_count', models.IntegerField(blank=True, default=0, verbose_name='Total Comment Count')),
                ('total_reaction_video_count', models.IntegerField(blank=True, default=0, verbose_name='Total Reaction Video Count')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Celebrity rating')),
                ('open_booking_count', models.IntegerField(blank=True, default=0, verbose_name='Open Booking Count')),
                ('recent_comment_count', models.IntegerField(blank=True, default=0, verbose_name='Recent Comment Count')),
                ('recent_reaction_video_count', models.IntegerField(blank=True, default=0, verbose_name='Recent Reaction Video Count')),
                ('recent_rating_count', models.IntegerField(blank=True, default=0, verbose_name='Recent Rating Count')),
                ('recent_tip_count', models.IntegerField(blank=True, default=0, verbose_name='Recent Tip Count')),
                ('recent_tip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Recent Tip Amount')),
                ('recent_deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Recent Deposit Amount')),
                ('recent_deposit_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Recent Deposit Date')),
                ('profile_share_count', models.IntegerField(blank=True, default=0, verbose_name='Profile Share Count')),
                ('last_profile_shared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Profile Shared Date')),
                ('video_share_count', models.IntegerField(blank=True, default=0, verbose_name='Video Share Count')),
                ('last_video_shared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Video Shared Date')),
                ('thirty_days_booking_count', models.IntegerField(blank=True, default=0, verbose_name='30 Days Booking Count')),
                ('one_twenty_days_booking_count', models.IntegerField(blank=True, default=0, verbose_name='120 Days Booking Count')),
                ('one_eighty_days_booking_count', models.IntegerField(blank=True, default=0, verbose_name='180 Days Booking Count')),
                ('has_biography', models.BooleanField(default=False, verbose_name='Check Biography')),
                ('has_referral', models.BooleanField(default=False, verbose_name='Check Referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
