# Generated by Django 2.1.5 on 2019-06-13 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0006_celebritydashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebritydashboard',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celebritydashboard',
            name='last_updated_by_update_API',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last updated by update API'),
        ),
        migrations.AddField(
            model_name='celebritydashboard',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='celebritydashboard',
            name='pending_payments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Pending Payments'),
        ),
        migrations.AlterField(
            model_name='celebritydashboard',
            name='recent_deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Recent Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='celebritydashboard',
            name='recent_tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Recent Tip Amount'),
        ),
        migrations.AlterField(
            model_name='celebritydashboard',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Earnings'),
        ),
    ]
