PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 32
IOS_UNIVERSAL_FILE_PATH = "../.well-known/apple-app-site-association"
ANDROID_CONFIG_KEY = "android_version"
IOS_CONFIG_KEY = "ios_version"
ANDROID = "android"
IOS = "ios"
BASE_URL = "https://stargramz.qburst.build/"
SHORT_BASE_URL = "stargramz.qburst.build/"
REDIRECT_LINK = "http://stargramz.qburst.build/applinks/reset?reset_id="
ANDROID_UNIVERSAL_FILE_PATH = "../.well-known/assetlinks.json"
