# Generated by Django 2.1.5 on 2019-03-21 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20190228_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadminnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
