version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y git
  pre_build:
    commands:
      - export REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
      - export DEPLOYMENT_TYPE=aws
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - chmod +x build-docker-images.sh
      - ./build-docker-images.sh
      - ./version.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${REGISTRY}backend-celery${IMAGE_TAG}
      - docker push ${REGISTRY}backend-gunicorn${IMAGE_TAG}
      - docker push ${REGISTRY}backend-nginx-${DEPLOYMENT_TYPE}${IMAGE_TAG}
      - docker push ${REGISTRY}backend-migration${IMAGE_TAG}
      - docker push ${REGISTRY}backend-console${IMAGE_TAG}
      - echo Writing image definitions files...
      - printf '[{"name":"celery-worker","imageUri":"%sbackend-celery%s"}]' $REGISTRY $IMAGE_TAG > imagedefinitions-celery-worker.json
      - printf '[{"name":"celery-beat","imageUri":"%sbackend-celery%s"}]' $REGISTRY $IMAGE_TAG > imagedefinitions-celery-beat.json
      - printf '[{"name":"gunicorn","imageUri":"%sbackend-gunicorn%s"}]' $REGISTRY $IMAGE_TAG > imagedefinitions-gunicorn.json
      - printf '[{"name":"nginx","imageUri":"%sbackend-nginx-%s%s"}]' $REGISTRY $DEPLOYMENT_TYPE $IMAGE_TAG > imagedefinitions-nginx.json
      - printf '[{"name":"migration","imageUri":"%sbackend-migration%s"}]' $REGISTRY $IMAGE_TAG > imagedefinitions-migration.json
      - printf '[{"name":"load-data","imageUri":"%sbackend-migration%s"}]' $REGISTRY $IMAGE_TAG > imagedefinitions-load-data.json
      - printf '[{"name":"console","imageUri":"%sbackend-console%s"}]' $REGISTRY $IMAGE_TAG > imagedefinitions-console.json
artifacts:
  files:
    - imagedefinitions-celery-worker.json
    - imagedefinitions-celery-beat.json
    - imagedefinitions-gunicorn.json
    - imagedefinitions-nginx.json
    - imagedefinitions-migration.json
    - imagedefinitions-load-data.json
    - imagedefinitions-console.json
  discard-paths: yes
