version: 0.2

env:
  variables:
    GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y openssh-client jq
      - mkdir -p ~/.ssh/ && chmod 700 ~/.ssh/
      - aws ssm get-parameter --name /codebuild/github/key.pem | jq -r .Parameter.Value > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
  pre_build:
    commands:
      - export REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
      - export DEPLOYMENT_TYPE=aws
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - chmod +x version.sh
      - ./version.sh 'git@github.com:Starsona/backend.git'
      - export BASE_IMAGE_TAG=":latest"
      - export IMAGE_TAG="$VERSION"
      - echo Build started on `date`
      - echo Building the Docker images...
      - chmod +x build-docker-images.sh
      - ./build-docker-images.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${REGISTRY}backend-celery${IMAGE_TAG}
      - docker push ${REGISTRY}backend-gunicorn${IMAGE_TAG}
      - docker push ${REGISTRY}backend-nginx-${DEPLOYMENT_TYPE}${IMAGE_TAG}
      - docker push ${REGISTRY}backend-migration${IMAGE_TAG}
      - echo Writing artifacts...
      - aws ssm get-parameter --name /env/staging/backend.json | jq ".Parameter.ImageTag = \"$IMAGE_TAG\"" > backend.json
      - aws ssm get-parameter --name /env/staging/vpc.json > vpc.json
artifacts:
  files:
    - backend.json
    - vpc.json
  discard-paths: yes
