version: '3.3'
services:
  gunicorn:
    image: starsona-gunicorn
    networks:
    - overlay
    ports:
    - "9003:9003"
    restart: on-failure
    depends_on:
    - postgres
    environment:
    - ENV
    - AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
    - AWS_STORAGE_BUCKET_NAME=${S3_AWS_STORAGE_BUCKET_NAME}
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EMAIL_PORT
    - EMAIL_USE_TLS
    - FCM_SERVER_KEY
    - STRIPE_WEB_HOOK
    - STRIPE_CLIENT_ID
    - STRIPE_SECRET_KEY
    - DATABASE_NAME
    - DATABASE_USER
    - DATABASE_PASSWORD
    - DATABASE_HOST
    - BRANCH_IO_KEY
    - QUEUE_BROKER_URL
    - QUEUE_BACKEND
    - QUEUE_HOST

  migration:
    image: starsona-migration
    networks:
    - overlay
    depends_on:
    - postgres
    environment:
    - ENV
    - DATABASE_NAME
    - DATABASE_USER
    - DATABASE_PASSWORD
    - DATABASE_HOST

  celery-beat:
    image: starsona-celery
    networks:
    - overlay
    restart: on-failure
    depends_on:
    - postgres
    command: ["celery", "-A", "main", "beat"]
    environment:
    - ENV
    - AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
    - AWS_STORAGE_BUCKET_NAME=${S3_AWS_STORAGE_BUCKET_NAME}
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EMAIL_PORT
    - EMAIL_USE_TLS
    - FCM_SERVER_KEY
    - STRIPE_WEB_HOOK
    - STRIPE_CLIENT_ID
    - STRIPE_SECRET_KEY
    - DATABASE_NAME
    - DATABASE_USER
    - DATABASE_PASSWORD
    - DATABASE_HOST
    - BRANCH_IO_KEY
    - QUEUE_BROKER_URL
    - QUEUE_BACKEND
    - QUEUE_HOST

  celery-worker:
    image: starsona-celery
    networks:
    - overlay
    restart: on-failure
    depends_on:
    - postgres
    - rabbitmq
    command: ["celery", "-A", "main", "worker"]
    environment:
    - ENV
    - AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
    - AWS_STORAGE_BUCKET_NAME=${S3_AWS_STORAGE_BUCKET_NAME}
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EMAIL_PORT
    - EMAIL_USE_TLS
    - FCM_SERVER_KEY
    - STRIPE_WEB_HOOK
    - STRIPE_CLIENT_ID
    - STRIPE_SECRET_KEY
    - DATABASE_NAME
    - DATABASE_USER
    - DATABASE_PASSWORD
    - DATABASE_HOST
    - BRANCH_IO_KEY
    - QUEUE_BROKER_URL
    - QUEUE_BACKEND
    - QUEUE_HOST

  postgres:
    image: postgres:9.5
    volumes:
    - /var/lib/postgresql/data
    networks:
    - overlay
    restart: on-failure
    environment:
    - POSTGRES_USER=${DATABASE_USER}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_DB=${DATABASE_NAME}
    - PGDATA=/var/lib/postgresql/data/pgdata

  rabbitmq:
    image: rabbitmq:3.7
    networks:
    - overlay
    restart: on-failure
    environment:
    - RABBITMQ_DEFAULT_USER=${QUEUE_USER}
    - RABBITMQ_DEFAULT_PASS=${QUEUE_PASSWORD}

  nginx:
    image: starsona-nginx-swarm
    hostname: ${SSL_SERVER_NAME}
    volumes:
    - /etc/letsencrypt
    networks:
    - overlay
    ports:
    - "80:80"
    - "443:443"
    restart: on-failure
    environment:
    - SSL_SERVER_NAME
    - SSL_SERVER_EMAIL

networks:
  overlay:

