version: '3.3'
services:
  loaddatas:
    build:
      context: ..
      dockerfile: docker/dockerfiles/starsona-migration
    image: starsona-migration
    networks:
    - overlay
    environment:
    - ENV
    - DATABASE_NAME
    - DATABASE_USER
    - DATABASE_PASSWORD
    - DATABASE_HOST
    command: ./loaddatas.sh

networks:
  overlay:

