# Generated by Django 2.1.5 on 2019-06-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videofavorites',
            options={'verbose_name': 'Video Like'},
        ),
    ]
