# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Feature Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Role Code')),
            ],
        ),
        migrations.CreateModel(
            name='RoleFeatureMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Feature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='features',
            field=models.ManyToManyField(related_name='features', through='role.RoleFeatureMapping', to='role.Feature'),
        ),
        migrations.AlterUniqueTogether(
            name='rolefeaturemapping',
            unique_together=set([('role', 'feature')]),
        ),
    ]
