# Generated by Django 2.1.5 on 2019-02-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolefeaturemapping',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.Feature'),
        ),
        migrations.AlterField(
            model_name='rolefeaturemapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.Role'),
        ),
    ]
