# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-29 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stargramz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramrequest',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_celebrity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stargramrequest',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_fan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stargramrequest',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_occasion', to='stargramz.Occasion'),
        ),
        migrations.AddField(
            model_name='reportabuse',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportabuse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_abuse', to='stargramz.Stargramrequest'),
        ),
        migrations.AddField(
            model_name='orderrelationship',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_occasion', to='stargramz.Occasion'),
        ),
        migrations.AddField(
            model_name='orderrelationship',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_relation', to='stargramz.OccasionRelationship'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='relationships',
            field=models.ManyToManyField(blank=True, through='stargramz.OrderRelationship', to='stargramz.OccasionRelationship'),
        ),
    ]
