# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='stargramvideo',
            name='comments_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Comments count'),
        ),
    ]
