# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-10 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stargramz', '0004_auto_20180816_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(1, 'Image'), (2, 'Video')], verbose_name='File type')),
                ('reaction_file', models.CharField(max_length=600, verbose_name='Reaction File')),
                ('file_thumbnail', models.CharField(blank=True, max_length=600, null=True, verbose_name='Thumbnail')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='Admin Approved')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='list order')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_reaction', to='stargramz.Stargramrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
