# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0007_auto_20181018_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['-id', '-created_date'], 'verbose_name': 'Reactions', 'verbose_name_plural': 'Reaction'},
        ),
        migrations.AddField(
            model_name='reaction',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
