# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-21 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stargramz', '0008_auto_20181219_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionAbuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('read_flag', models.BooleanField(default=False, verbose_name='Verified abuse')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_abuse', to='stargramz.Reaction')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reported_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
