# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-01 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0010_auto_20190115_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramrequest',
            name='reprocessed',
            field=models.BooleanField(default=False, verbose_name='Reprocessing'),
        ),
        migrations.AlterField(
            model_name='stargramrequest',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Payment Approved'), (2, 'Pending'), (3, 'Processing'), (4, 'Video Approval'), (5, 'Cancelled'), (6, 'Completed'), (7, 'Reprocessing')], default=0),
        ),
    ]
