# Generated by Django 2.1.5 on 2019-03-20 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0012_auto_20190228_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reactionabuse',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stargramrequest',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_celebrity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stargramrequest',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_fan', to=settings.AUTH_USER_MODEL),
        ),
    ]
