# Generated by Django 2.1.5 on 2019-03-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0013_auto_20190321_0514'),
        ('stargramz', '0013_auto_20190320_0652'),
    ]

    operations = [
    ]
