# Generated by Django 2.1.5 on 2019-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0014_merge_20190321_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Type 0'), (1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3'), (4, 'Type 4'), (5, 'Type 5'), (6, 'Type 6'), (7, 'Type 7'), (8, 'Type 8')], default=1),
        ),
    ]
