# Generated by Django 2.1.5 on 2019-06-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0015_occasion_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramrequest',
            name='booking_statement',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Booking Statement'),
        ),
    ]
