# Generated by Django 2.1.5 on 2019-06-21 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0016_stargramrequest_booking_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramrequest',
            name='recent_activity_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
