# Generated by Django 2.1.5 on 2019-06-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0017_stargramrequest_recent_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramvideo',
            name='public_visibility',
            field=models.BooleanField(default=True, verbose_name='New Public Visibility'),
        ),
    ]
