# Generated by Django 2.1.5 on 2019-07-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stargramz', '0018_stargramvideo_public_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargramrequest',
            name='honor_audio_file',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='stargramrequest',
            name='host_audio_file',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
