version: 0.2

env:
  variables:
    GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y openssh-client jq
      - mkdir -p ~/.ssh/ && chmod 700 ~/.ssh/
      - aws ssm get-parameter --name /codebuild/github/backend/key.pem | jq -r .Parameter.Value > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
  pre_build:
    commands:
      - "export AWS_ACCOUNT_ID=`echo $CODEBUILD_BUILD_ARN | cut -d: -f5`"
      - export REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
      - export DEPLOYMENT_TYPE=aws
      - echo Reading parameters from SSM...
      - aws ssm get-parameter --name ${PARAMETERS} | jq -r .Parameter.Value > parameters.json
      - cat parameters.json
      - export VERSION=`cat parameters.json | jq -r .Parameters.Version`
      - export GIT_BRANCH=`cat parameters.json | jq -r .Parameters.GitBranch`
      - export BASE_IMAGE_TAG=`cat parameters.json | jq -r .Parameters.BaseImageTag`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - chmod +x aws/scripts/version.sh
      - aws/scripts/version.sh 'git@github.com:Starsona/backend.git'
      - export IMAGE_TAG=:`cat .version`
      - echo Building the Docker images version${IMAGE_TAG}...
      - chmod +x docker/build-docker-images.sh
      - docker/build-docker-images.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${REGISTRY}backend-celery${IMAGE_TAG}
      - docker push ${REGISTRY}backend-gunicorn${IMAGE_TAG}
      - docker push ${REGISTRY}backend-nginx-${DEPLOYMENT_TYPE}${IMAGE_TAG}
      - docker push ${REGISTRY}backend-migration${IMAGE_TAG}
      - echo Writing artifacts...
      - aws ssm get-parameter --name /env/staging/backend/backend.json | jq -r .Parameter.Value | jq ".Parameters.ImageTag = \"${IMAGE_TAG}\"" > staging-backend.json
      - aws ssm get-parameter --name /env/hotfix/backend/backend.json | jq -r .Parameter.Value | jq ".Parameters.ImageTag = \"${IMAGE_TAG}\"" > hotfix-backend.json
      - aws ssm get-parameter --name /env/upgrade/backend/backend.json | jq -r .Parameter.Value | jq ".Parameters.ImageTag = \"${IMAGE_TAG}\"" > upgrade-backend.json
      - aws ssm get-parameter --name /env/production/backend/backend.json | jq -r .Parameter.Value | jq ".Parameters.ImageTag = \"${IMAGE_TAG}\"" > production-backend.json
      - cat staging-backend.json hotfix-backend.json upgrade-backend.json production-backend.json
artifacts:
  files:
    - staging-backend.json
    - hotfix-backend.json
    - upgrade-backend.json
    - production-backend.json
  discard-paths: yes
