from utilities.konstants import Konstants, K
COUNTRIES = Konstants(
    K(option=-1, label='Select country'),
    K(AF=0, label='Afghanistan'),
    K(AL=1, label='Albania'),
    K(DZ=2, label='Algeria'),
    K(AS=3, label='American Samoa'),
    K(AD=4, label='Andorra'),
    K(AO=5, label='Angola'),
    K(AI=6, label='Anguilla'),
    K(AQ=7, label='Antarctica'),
    K(AG=8, label='Antigua And Barbuda'),
    K(AR=9, label='Argentina'),
    K(AM=10, label='Armenia'),
    K(AW=11, label='Aruba'),
    K(AU=12, label='Australia'),
    K(AT=13, label='Austria'),
    K(AZ=14, label='Azerbaijan'),
    K(BS=15, label='Bahamas'),
    K(BH=16, label='Bahrain'),
    K(BD=17, label='Bangladesh'),
    K(BB=18, label='Barbados'),
    K(BY=19, label='Belarus'),
    K(BE=20, label='Belgium'),
    K(BZ=21, label='Belize'),
    K(BJ=22, label='Benin'),
    K(BM=23, label='Bermuda'),
    K(BT=24, label='Bhutan'),
    K(BO=25, label='Bolivia'),
    K(BA=26, label='Bosnia And Herzegovina'),
    K(BW=27, label='Botswana'),
    K(BV=28, label='Bouvet Island'),
    K(BR=29, label='Brazil'),
    K(IO=30, label='British Indian Ocean Territory'),
    K(BN=31, label='Brunei Darussalam'),
    K(BG=32, label='Bulgaria'),
    K(BF=33, label='Burkina Faso'),
    K(BI=34, label='Burundi'),
    K(KH=35, label='Cambodia'),
    K(CM=36, label='Cameroon'),
    K(CA=37, label='Canada'),
    K(CV=38, label='Cape Verde'),
    K(KY=39, label='Cayman Islands'),
    K(CF=40, label='Central African Republic'),
    K(TD=41, label='Chad'),
    K(CL=42, label='Chile'),
    K(CN=43, label='China'),
    K(CX=44, label='Christmas Island'),
    K(CC=45, label='Cocos (keeling) Islands'),
    K(CO=46, label='Colombia'),
    K(KM=47, label='Comoros'),
    K(CG=48, label='Congo'),
    K(CD=49, label='Congo, The Democratic Republic Of The'),
    K(CK=50, label='Cook Islands'),
    K(CR=51, label='Costa Rica'),
    K(CI=52, label='Cote Divoire'),
    K(HR=53, label='Croatia'),
    K(CU=54, label='Cuba'),
    K(CY=55, label='Cyprus'),
    K(CZ=56, label='Czech Republic'),
    K(DK=57, label='Denmark'),
    K(DJ=58, label='Djibouti'),
    K(DM=59, label='Dominica'),
    K(DO=60, label='Dominican Republic'),
    K(TP=61, label='East Timor'),
    K(EC=62, label='Ecuador'),
    K(EG=63, label='Egypt'),
    K(SV=64, label='El Salvador'),
    K(GQ=65, label='Equatorial Guinea'),
    K(ER=66, label='Eritrea'),
    K(EE=67, label='Estonia'),
    K(ET=68, label='Ethiopia'),
    K(FK=69, label='Falkland Islands (malvinas)'),
    K(FO=70, label='Faroe Islands'),
    K(FJ=71, label='Fiji'),
    K(FI=72, label='Finland'),
    K(FR=73, label='France'),
    K(GF=74, label='French Guiana'),
    K(PF=75, label='French Polynesia'),
    K(TF=76, label='French Southern Territories'),
    K(GA=77, label='Gabon'),
    K(GM=78, label='Gambia'),
    K(GE=79, label='Georgia'),
    K(DE=80, label='Germany'),
    K(GH=81, label='Ghana'),
    K(GI=82, label='Gibraltar'),
    K(GR=83, label='Greece'),
    K(GL=84, label='Greenland'),
    K(GD=85, label='Grenada'),
    K(GP=86, label='Guadeloupe'),
    K(GU=87, label='Guam'),
    K(GT=88, label='Guatemala'),
    K(GN=89, label='Guinea'),
    K(GW=90, label='Guinea-bissau'),
    K(GY=91, label='Guyana'),
    K(HT=92, label='Haiti'),
    K(HM=93, label='Heard Island And Mcdonald Islands'),
    K(VA=94, label='Holy See (vatican City State)'),
    K(HN=95, label='Honduras'),
    K(HK=96, label='Hong Kong'),
    K(HU=97, label='Hungary'),
    K(IS=98, label='Iceland'),
    K(IN=99, label='India'),
    K(ID=100, label='Indonesia'),
    K(IR=101, label='Iran, Islamic Republic Of'),
    K(IQ=102, label='Iraq'),
    K(IE=103, label='Ireland'),
    K(IL=104, label='Israel'),
    K(IT=105, label='Italy'),
    K(JM=106, label='Jamaica'),
    K(JP=107, label='Japan'),
    K(JO=108, label='Jordan'),
    K(KZ=109, label='Kazakstan'),
    K(KE=110, label='Kenya'),
    K(KI=111, label='Kiribati'),
    K(KP=112, label='Korea, Democratic Peoples Republic Of'),
    K(KR=113, label='Korea, Republic Of'),
    K(KV=114, label='Kosovo'),
    K(KW=115, label='Kuwait'),
    K(KG=116, label='Kyrgyzstan'),
    K(LA=117, label='Lao Peoples Democratic Republic'),
    K(LV=118, label='Latvia'),
    K(LB=119, label='Lebanon'),
    K(LS=120, label='Lesotho'),
    K(LR=121, label='Liberia'),
    K(LY=122, label='Libyan Arab Jamahiriya'),
    K(LI=123, label='Liechtenstein'),
    K(LT=124, label='Lithuania'),
    K(LU=125, label='Luxembourg'),
    K(MO=126, label='Macau'),
    K(MK=127, label='Macedonia, The Former Yugoslav Republic Of'),
    K(MG=128, label='Madagascar'),
    K(MW=129, label='Malawi'),
    K(MY=130, label='Malaysia'),
    K(MV=131, label='Maldives'),
    K(ML=132, label='Mali'),
    K(MT=133, label='Malta'),
    K(MH=134, label='Marshall Islands'),
    K(MQ=135, label='Martinique'),
    K(MR=136, label='Mauritania'),
    K(MU=137, label='Mauritius'),
    K(YT=138, label='Mayotte'),
    K(MX=139, label='Mexico'),
    K(FM=140, label='Micronesia, Federated States Of'),
    K(MD=141, label='Moldova, Republic Of'),
    K(MC=142, label='Monaco'),
    K(MN=143, label='Mongolia'),
    K(MS=144, label='Montserrat'),
    K(ME=145, label='Montenegro'),
    K(MA=146, label='Morocco'),
    K(MZ=147, label='Mozambique'),
    K(MM=148, label='Myanmar'),
    K(NA=149, label='Namibia'),
    K(NR=150, label='Nauru'),
    K(NP=151, label='Nepal'),
    K(NL=152, label='Netherlands'),
    K(AN=153, label='Netherlands Antilles'),
    K(NC=154, label='New Caledonia'),
    K(NZ=155, label='New Zealand'),
    K(NI=156, label='Nicaragua'),
    K(NE=157, label='Niger'),
    K(NG=158, label='Nigeria'),
    K(NU=159, label='Niue'),
    K(NF=160, label='Norfolk Island'),
    K(MP=161, label='Northern Mariana Islands'),
    K(NO=162, label='Norway'),
    K(OM=163, label='Oman'),
    K(PK=164, label='Pakistan'),
    K(PW=165, label='Palau'),
    K(PS=166, label='Palestinian Territory, Occupied'),
    K(PA=167, label='Panama'),
    K(PG=168, label='Papua New Guinea'),
    K(PY=169, label='Paraguay'),
    K(PE=170, label='Peru'),
    K(PH=171, label='Philippines'),
    K(PN=172, label='Pitcairn'),
    K(PL=173, label='Poland'),
    K(PT=174, label='Portugal'),
    K(PR=175, label='Puerto Rico'),
    K(QA=176, label='Qatar'),
    K(RE=177, label='Reunion'),
    K(RO=178, label='Romania'),
    K(RU=179, label='Russian Federation'),
    K(RW=180, label='Rwanda'),
    K(SH=181, label='Saint Helena'),
    K(KN=182, label='Saint Kitts And Nevis'),
    K(LC=183, label='Saint Lucia'),
    K(PM=184, label='Saint Pierre And Miquelon'),
    K(VC=185, label='Saint Vincent And The Grenadines'),
    K(WS=186, label='Samoa'),
    K(SM=187, label='San Marino'),
    K(ST=188, label='Sao Tome And Principe'),
    K(SA=189, label='Saudi Arabia'),
    K(SN=190, label='Senegal'),
    K(RS=191, label='Serbia'),
    K(SC=192, label='Seychelles'),
    K(SL=193, label='Sierra Leone'),
    K(SG=194, label='Singapore'),
    K(SK=195, label='Slovakia'),
    K(SI=196, label='Slovenia'),
    K(SB=197, label='Solomon Islands'),
    K(SO=198, label='Somalia'),
    K(ZA=199, label='South Africa'),
    K(GS=200, label='South Georgia And The South Sandwich Islands'),
    K(ES=201, label='Spain'),
    K(LK=202, label='Sri Lanka'),
    K(SD=203, label='Sudan'),
    K(SR=204, label='Suriname'),
    K(SJ=205, label='Svalbard And Jan Mayen'),
    K(SZ=206, label='Swaziland'),
    K(SE=207, label='Sweden'),
    K(CH=208, label='Switzerland'),
    K(SY=209, label='Syrian Arab Republic'),
    K(TW=210, label='Taiwan, Province Of China'),
    K(TJ=211, label='Tajikistan'),
    K(TZ=212, label='Tanzania, United Republic Of'),
    K(TH=213, label='Thailand'),
    K(TG=214, label='Togo'),
    K(TK=215, label='Tokelau'),
    K(TO=216, label='Tonga'),
    K(TT=217, label='Trinidad And Tobago'),
    K(TN=218, label='Tunisia'),
    K(TR=219, label='Turkey'),
    K(TM=220, label='Turkmenistan'),
    K(TC=221, label='Turks And Caicos Islands'),
    K(TV=222, label='Tuvalu'),
    K(UG=223, label='Uganda'),
    K(UA=224, label='Ukraine'),
    K(AE=225, label='United Arab Emirates'),
    K(GB=226, label='United Kingdom'),
    K(US=227, label='United States'),
    K(UM=228, label='United States Minor Outlying Islands'),
    K(UY=229, label='Uruguay'),
    K(UZ=230, label='Uzbekistan'),
    K(VU=231, label='Vanuatu'),
    K(VE=232, label='Venezuela'),
    K(VN=233, label='Viet Nam'),
    K(VG=234, label='Virgin Islands, British'),
    K(VI=235, label='Virgin Islands, U.s.'),
    K(WF=236, label='Wallis And Futuna'),
    K(EH=237, label='Western Sahara'),
    K(YE=238, label='Yemen'),
    K(ZM=239, label='Zambia'),
    K(ZW=240, label='Zimbabwe')
)
